<a href="https://colab.research.google.com/github/saisai257274/NLP-1/blob/main/Lab_Assignment_15_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Importing the libraries and dependencies**

In [ ]:
import tensorflow as tf
import tensorflow_hub as hub
import tensorflow_text as text
import numpy as np

# **Task 1 Using ELMo**

# **Loading the ELMo Word Embedding Model**

In [ ]:
elmo = hub.load("https://tfhub.dev/google/elmo/3")

# **Create the text corpus**

In [ ]:
sentences = [
    "The bank will not approve the loan",
    "He sat on the river bank"
]

# **Convert the tokens into embedding vectors**

In [ ]:
embeddings = elmo.signatures['default'](tf.constant(sentences))['elmo']
display(embeddings.shape)

TensorShape([2, 7, 1024])

# **Display the embedding values of the word 'bank'**

In [ ]:
tokenized = []
for sentence in sentences:
  tokenized.append(sentence.split())

idx1 = tokenized[0].index("bank")
idx2 = tokenized[1].index("bank")

bank_emb_1 = embeddings[0][idx1]
bank_emb_2 = embeddings[1][idx2]

print("First 10 values of the embeddings for the word 'bank' in the first sentence:")
print(bank_emb_1[:10])

print("First 10 values of the embeddings for the word 'bank' in the second sentence:")
print(bank_emb_2[:10])

First 10 values of the embeddings for the word 'bank' in the first sentence:
tf.Tensor(
[-0.9086765  -0.36578754 -0.07339765  0.586675    0.22132948 -0.7657321
 -0.11816446 -0.30227882 -0.06137528  0.1695182 ], shape=(10,), dtype=float32)
First 10 values of the embeddings for the word 'bank' in the second sentence:
tf.Tensor(
[-0.15614763  0.28345656 -0.08914638  0.2069506   0.1524184  -0.2037305
 -0.10812807  0.03747292  0.5214868   0.35352594], shape=(10,), dtype=float32)


# **Compare the context using Cosine Similarity**

In [ ]:
def cosine_similarity(a, b):
  return np.dot(a, b) / (np.linalg.norm(a) * np.linalg.norm(b))

similarity = cosine_similarity(bank_emb_1, bank_emb_2)
print("Cosine Similarity Score:", similarity)

Cosine Similarity Score: 0.57813895


# **Task 2 Using ELMo**

# **Create the text corpus**

In [ ]:
text_corpus = [
    "The bat is flying",
    "He hit the ball with the bat"
]

# **Convert the tokens into embeddings vectors**

In [ ]:
text_embeddings = elmo.signatures['default'](tf.constant(text_corpus))['elmo']
display(text_embeddings.shape)

TensorShape([2, 7, 1024])

# **Display the embedding vectors for the word 'bat'**

In [ ]:
text_tokenized = []
for token in text_corpus:
  text_tokenized.append(token.split())

index1 = text_tokenized[0].index("bat")
index2 = text_tokenized[1].index("bat")

bat_emb_1 = text_embeddings[0][index1]
bat_emb_2 = text_embeddings[1][index2]

print("First 10 values of the embeddings for the word 'bat' in the first sentence:")
print(bat_emb_1[:10])

print("First 10 values of the embeddings for the word 'bat' in the second sentence:")
print(bat_emb_2[:10])

First 10 values of the embeddings for the word 'bat' in the first sentence:
tf.Tensor(
[-0.45903727 -0.27516434 -0.26348162 -0.12380227 -0.11530864 -0.45880768
 -0.12675564 -0.12455821 -0.2630463  -0.1839562 ], shape=(10,), dtype=float32)
First 10 values of the embeddings for the word 'bat' in the second sentence:
tf.Tensor(
[ 0.2558997  -0.06854984 -0.07069111 -0.43740696 -0.12692025 -0.11348379
  0.15598667  0.12158953 -0.32072857 -0.14388369], shape=(10,), dtype=float32)


# **Compare the context using Cosine Similarity**

In [ ]:
def cosine_similarity_score(a, b):
  return np.dot(a, b) / (np.linalg.norm(a) * np.linalg.norm(b))

similarity_score = cosine_similarity_score(bat_emb_1, bat_emb_2)
print("Cosine Similarity Score:", similarity_score)

Cosine Similarity Score: 0.6408916


# **Task 3 Using BERT**

# **Get the text corpus**

In [ ]:
sentences = [
    "The bat is flying",
    "He hit the ball with a bat"
]

# **Load the Input Embedding Layer and BERT Model**

In [ ]:
preprocess = hub.load("https://tfhub.dev/tensorflow/bert_en_uncased_preprocess/3")
bert_model = hub.load("https://tfhub.dev/tensorflow/bert_en_uncased_L-12_H-768_A-12/3")

# **Output of Input Embedding Layers**

In [ ]:
inputs = preprocess(sentences)
print(inputs.keys())

dict_keys(['input_type_ids', 'input_mask', 'input_word_ids'])


# **Sending the Input Layer Embeddings to BERT Model**

In [ ]:
outputs = bert_model(inputs)

embeddings = outputs['sequence_output']
print("Embeddings shape:", embeddings.shape)

Embeddings shape: (2, 128, 768)


In [ ]:
tokenizer = hub.KerasLayer("https://tfhub.dev/tensorflow/bert_en_uncased_preprocess/3")

tokens = preprocess(sentences)['input_word_ids']
print(tokens)

tf.Tensor(
[[ 101 1996 7151 2003 3909  102    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0]
 [ 101 2002 2718 1996 3608 2007 1037 7151  102    0    0    0    0    0
     0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    

# **Display the embeddings of the tokens**

In [ ]:
bat_emb_1 = embeddings[0][2]
bat_emb_2 = embeddings[1][7]

print("First 10 values of the embeddings of the word 'bat' in the first sentence:")
print(bat_emb_1[:10])

print("First 10 values of the embeddings of the word 'bat' in the second sentence:")
print(bat_emb_2[:10])

First 10 values of the embeddings of the word 'bat' in the first sentence:
tf.Tensor(
[-6.0895458e-05  2.6044571e-01  1.2677926e-01 -2.8091672e-01
  1.3292238e-02 -4.8430103e-01  7.0899075e-01  7.3061740e-01
  2.0883048e-01 -7.8647310e-01], shape=(10,), dtype=float32)
First 10 values of the embeddings of the word 'bat' in the second sentence:
tf.Tensor(
[-0.06056872 -0.90724915 -0.06744897 -0.27453673 -0.4663377   0.04165859
  0.23526248  0.35729024  0.9171281  -0.67234385], shape=(10,), dtype=float32)


# **Compare the context using Cosine Similarity**

In [ ]:
def cosine_similarity(a, b):
  return np.dot(a, b) / (np.linalg.norm(a) * np.linalg.norm(b))

similarity = cosine_similarity(bat_emb_1, bat_emb_2)
print("Cosine Similarity Score:", similarity)

Cosine Similarity Score: 0.4342774


# **Task 4 Using BERT**

# **Creating the text corpus**

In [ ]:
text_corpus = [
    "The bank will not approve the loan",
    "He sat on the river bank"
]

# **Output of Input Embedding Layers**

In [ ]:
text_inputs = preprocess(text_corpus)
print(text_inputs.keys())

dict_keys(['input_type_ids', 'input_mask', 'input_word_ids'])


# **Sending the Input Layer Embeddings to BERT Model**

In [ ]:
text_outputs = bert_model(text_inputs)

text_embeddings = text_outputs['sequence_output']
print("Embeddings shape:", text_embeddings.shape)

Embeddings shape: (2, 128, 768)


In [ ]:
text_tokenizer = hub.KerasLayer("https://tfhub.dev/tensorflow/bert_en_uncased_preprocess/3")

text_tokens = preprocess(text_corpus)['input_word_ids']
print(text_tokens)

tf.Tensor(
[[  101  1996  2924  2097  2025 14300  1996  5414   102     0     0     0
      0     0     0     0     0     0     0     0     0     0     0     0
      0     0     0     0     0     0     0     0     0     0     0     0
      0     0     0     0     0     0     0     0     0     0     0     0
      0     0     0     0     0     0     0     0     0     0     0     0
      0     0     0     0     0     0     0     0     0     0     0     0
      0     0     0     0     0     0     0     0     0     0     0     0
      0     0     0     0     0     0     0     0     0     0     0     0
      0     0     0     0     0     0     0     0     0     0     0     0
      0     0     0     0     0     0     0     0     0     0     0     0
      0     0     0     0     0     0     0     0]
 [  101  2002  2938  2006  1996  2314  2924   102     0     0     0     0
      0     0     0     0     0     0     0     0     0     0     0     0
      0     0     0     0     0     0     0     0 

# **Display the embeddings of the tokens**

In [ ]:
bank_emb_1 = text_embeddings[0][2]
bank_emb_2 = text_embeddings[1][6]

print("First 10 values of the embeddings for the word 'bank' in the first sentence:")
print(bank_emb_1[:10])

print("First 10 values of the embeddings for the word 'bank' in the second sentence:")
print(bank_emb_2[:10])

First 10 values of the embeddings for the word 'bank' in the first sentence:
tf.Tensor(
[ 0.2904349  -0.32690698  0.41449463  0.29487795  1.2237239   0.18653744
 -0.49868193  0.6392799   0.091379    0.15223761], shape=(10,), dtype=float32)
First 10 values of the embeddings for the word 'bank' in the second sentence:
tf.Tensor(
[-0.5490642  -0.6723898  -0.7039849   0.00643292 -0.5798305   0.315542
  0.22425273  0.8700532  -0.11308768 -0.9146493 ], shape=(10,), dtype=float32)


# **Compare the context using Cosine Similarity**

In [ ]:
def cosine_similarity_score(a, b):
  return np.dot(a, b) / (np.linalg.norm(a) * np.linalg.norm(b))

similarity_score = cosine_similarity_score(bank_emb_1, bank_emb_2)
print("Cosine Similarity Score:", similarity_score)

Cosine Similarity Score: 0.3043947


# **Task 5: Text Classification Using ELMo + Naive-Bayes**

# **Import the libraries and dependencies**

In [ ]:
import tensorflow as tf
import tensorflow_hub as hub
import numpy as np

from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

# **Creating the text corpus**

In [ ]:
sentences = [
    "Win money now",
    "Claim your prize",
    "Hello how are you",
    "Let's meet tomorrow",
    "Free lottery ticket",
    "Are you coming today"
]

labels = [1, 1, 0, 0, 1, 0]

# **Loading the ELMo Model**

In [ ]:
elmo = hub.load("https://tfhub.dev/google/elmo/3")

# **Convert the tokens into embeddings**

In [ ]:
embeddings = elmo.signatures['default'](tf.constant(sentences))['elmo']

print("Shape:", embeddings.shape)

Shape: (6, 4, 1024)


# **Convert the embeddings into sentence embeddings**

In [ ]:
sentence_embeddings = tf.reduce_mean(embeddings, axis=1)

X = sentence_embeddings.numpy()
y = np.array(labels)

print("Feature shape:", X.shape)

Feature shape: (6, 1024)


# **Split the data into training and testing**

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# **Training the model**

In [ ]:
model = GaussianNB()
model.fit(X_train, y_train)

GaussianNB()

# **Testing the model**

In [ ]:
y_pred = model.predict(X_test)

print("Predictions:", y_pred)
print("Actual:", y_test)

Predictions: [0 0]
Actual: [1 1]


# **Evaluating the model**

In [ ]:
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

Accuracy: 0.0


# **Prediction on new document**

In [ ]:
new_sentence = ["Congratulations! You won a free ticket"]

new_emb = elmo.signatures['default'](tf.constant(new_sentence))['elmo']
new_emb = tf.reduce_mean(new_emb, axis=1)

prediction = model.predict(new_emb.numpy())

print("Prediction:", "Spam" if prediction[0] == 1 else "Not Spam")

Prediction: Not Spam


# **Task 6: Text Classification Using BERT + Naive-Bayes**

# **Loading the Input Embedding Layer and BERT Model**

In [ ]:
preprocess = hub.load("https://tfhub.dev/tensorflow/bert_en_uncased_preprocess/3")
bert_model = hub.load("https://tfhub.dev/tensorflow/bert_en_uncased_L-12_H-768_A-12/3")

# **Output of the Input Embedding Layers**

In [ ]:
bert_inputs = preprocess(sentences)

# **Sending the Input Layer Embeddings into BERT Model**

In [ ]:
bert_outputs = bert_model(bert_inputs)

bert_features = bert_outputs['pooled_output'].numpy()

# **Splitting the data, training, testing and evaluating the model**

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(bert_features, labels, test_size=0.2, random_state=42)

nb_bert = GaussianNB()
nb_bert.fit(X_train, y_train)

y_pred_bert = nb_bert.predict(X_test)
acc_bert = accuracy_score(y_test, y_pred_bert)

print("BERT Accuracy:", acc_bert)

BERT Accuracy: 0.0
